In [4]:
import pandas as pd
import numpy as np

In [6]:
final_df = pd.read_csv('final_customer_churn_dataset.csv')

In [19]:
churn_df = pd.read_csv('Churn_Prediction_Output.csv')

In [21]:
churn_df

,Total_Transactions,Next_Quarter_Revenue_USD,Renewal_Risk_Flag,ACV_USD,Last_Invoice_Amount_USD,Avg_Revenue_USD,Avg_API_Calls,Total_Billed_USD,API_Calls_Monthly,Avg_Tax,...,Avg_Errors,Avg_Session_Min,Negative,Onboarding_Completed,QBR_Completed_Last_6M,Competitor_Mentioned,Downsell_Requested,Actual_Churn,Predicted_Churn,Churn_Probability
0,11,26,1,132,29,36.181818,3166.416667,420,3707,12.181818,...,5.444444,7.977778,7,0,0,0,1,0,0,4.316189e-09
1,8,13188,1,39278,10354,1248.625000,51816.714286,9989,38883,12.375000,...,4.928571,16.417857,2,1,0,1,0,0,0,3.872796e-09
2,9,18867,1,68832,16687,11364.444444,63639.250000,103472,51050,7.777778,...,4.888889,26.677778,3,1,1,1,0,0,0,2.417322e-09
3,3,189,0,9097,1940,422.000000,4594.166667,1266,5138,8.333333,...,5.333333,3.988889,4,1,0,1,0,1,1,1.000000e+00
4,8,4295,1,14043,3189,1054.000000,59325.527778,8600,47489,14.500000,...,4.750000,20.111111,0,1,1,0,0,0,0,1.063369e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,11,16,1,90,23,22.454545,5179.666667,264,4903,12.000000,...,3.666667,12.633333,9,1,0,0,0,0,0,4.320436e-08
4996,9,2675,0,12872,3211,1507.777778,3347.833333,14541,3444,13.444444,...,4.944444,7.194444,15,1,0,0,0,0,0,2.903121e-09
4997,14,372,1,1098,258,144.428571,39874.058824,2063,34502,9.714286,...,4.941176,19.494118,2,1,0,1,1,0,0,6.010405e-11
4998,13,6578,1,21989,5799,2272.153846,70275.972222,29980,54911,7.384615,...,5.361111,21.611111,0,1,1,0,0,0,0,2.835335e-09
4999,11,481,2,2935,629,1150.363636,3799.166667,12931,4320,5.090909,...,5.305556,7.672222,2,0,1,1,1,0,0,1.215661e-08

In [12]:
revenue_df = pd.read_csv('revenue_predictions.csv')
revenue_df

,Customer_ID,Geo_ID,Industry_ID,Product_ID,Cluster_Label,Account_Tier,Company_Size,Company_Age_Years,Employees,Legal_Entity_Type,...,Pending,Resolved,Workaround,Negative,Neutral,Positive,FollowUp_Count,SLA_Breach_Count,Manager_Escalation_Count,Predicted_Next_Quarter_Revenue
0,11177,121,4,27,At-Risk SMB,Platinum,Startup (<50),10,91.0,Ltd,...,0,2,0,7,3,3,4,2,0,36.364887
1,14771,44,5,25,High-Growth Startup,Gold,Startup (<50),1,309.0,AG,...,0,0,0,2,0,1,1,0,0,11696.725000
2,11091,6,7,27,High Revenue Loyal,Bronze,Mid-Market (251-1000),7,990.0,GmbH,...,0,4,0,3,3,3,2,1,0,19385.465000
3,14818,1,3,17,At-Risk SMB,Strategic,Startup (<50),2,121.0,LLC,...,0,3,0,4,2,5,6,1,1,743.993840
4,14376,19,10,18,High Revenue Loyal,Bronze,SMB (50-250),9,245.0,Sdn Bhd,...,0,0,0,0,0,2,1,0,0,3344.757300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,13744,127,3,27,At-Risk SMB,Strategic,Startup (<50),7,293.0,SAS,...,1,2,0,9,4,3,5,1,1,35.229910
4996,13446,5,5,2,At-Risk SMB,Silver,Mid-Market (251-1000),11,54.0,KK,...,1,3,1,15,4,2,7,0,0,1935.031100
4997,10065,156,3,10,High-Growth Startup,Silver,Enterprise (1000+),11,733.0,GmbH,...,0,0,0,2,3,7,2,0,0,426.741730
4998,12774,163,9,6,High Revenue Loyal,Strategic,Mid-Market (251-1000),6,2027.0,Ltd,...,0,0,0,0,2,2,1,0,0,6353.195000
4999,10035,100,6,16,At-Risk SMB,Bronze,Mid-Market (251-1000),7,317.0,BV,...,0,3,0,2,5,1,3,0,0,623.576230

In [15]:
churn_df

,Total_Transactions,Next_Quarter_Revenue_USD,Renewal_Risk_Flag,ACV_USD,Last_Invoice_Amount_USD,Avg_Revenue_USD,Avg_API_Calls,Total_Billed_USD,API_Calls_Monthly,Avg_Tax,...,Avg_Errors,Avg_Session_Min,Negative,Onboarding_Completed,QBR_Completed_Last_6M,Competitor_Mentioned,Downsell_Requested,Actual_Churn,Predicted_Churn,Churn_Probability
0,9,11,2,78,20,8.888889,6005.500000,82,6324,5.666667,...,4.937500,12.400000,9,1,1,1,0,0,0,3.389801e-06
1,16,30557,1,105212,27124,52375.500000,62071.305556,839069,49083,5.437500,...,5.000000,30.188889,0,1,1,1,0,0,0,3.095185e-09
2,8,7128,1,29398,7010,1664.375000,11431.454545,13315,10418,10.750000,...,4.333333,5.366667,3,1,1,1,0,0,0,2.275802e-09
3,18,2098,0,13848,3078,6777.444444,4681.000000,122241,4446,11.888889,...,3.333333,3.133333,8,0,0,0,1,0,0,3.266740e-09
4,10,15600,1,64784,15797,7043.100000,82880.805556,70480,65001,5.400000,...,5.027778,25.936111,2,1,1,0,0,0,0,3.070505e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,14,8393,1,23870,6150,3820.071429,28784.000000,54252,27107,6.357143,...,5.666667,13.766667,0,1,1,0,0,0,0,2.223664e-09
996,2,338,1,16352,3482,3600.000000,63453.000000,7200,50787,10.000000,...,5.388889,25.425000,2,1,1,0,0,1,1,1.000000e+00
997,13,4404,1,16186,4873,2504.076923,20412.305556,34178,18545,8.846154,...,5.333333,17.011111,3,1,1,0,0,0,0,2.340539e-09
998,13,92,1,276,60,25.384615,23144.083333,344,20290,8.076923,...,5.750000,15.825000,0,1,1,0,0,0,0,2.640093e-09
999,13,188,1,684,176,112.000000,65762.250000,1461,51752,10.000000,...,4.718750,28.531250,4,1,1,0,0,0,0,1.609292e-09

In [7]:
final_df.columns.tolist()

['Customer_ID',
 'Geo_ID',
 'Industry_ID',
 'Product_ID',
 'Cluster_Label',
 'Account_Tier',
 'Company_Size',
 'Company_Age_Years',
 'Employees',
 'Legal_Entity_Type',
 'HQ_vs_Billing',
 'Tenure_Months',
 'Contract_Type',
 'Contract_Start_Date',
 'Contract_End_Date',
 'Renewal_Probability',
 'CSM_Assigned',
 'CSM_Name',
 'Executive_Sponsor',
 'Health_Score',
 'Onboarding_Completed',
 'QBR_Completed_Last_6M',
 'Last_Training_Days_Ago',
 'Licenses_Purchased',
 'Daily_Active_Users',
 'Feature_Adoption_Pct',
 'API_Calls_Monthly',
 'Mobile_Users_Pct',
 'Sessions_Per_User_Day',
 'Avg_Session_Minutes',
 'Integrations_Count',
 'Custom_Reports_Count',
 'Automations_Active',
 'Support_Tickets',
 'Escalated_Tickets',
 'CSAT_Score',
 'NPS_Score',
 'Subscription_Value_Local',
 'Discount_Pct',
 'ACV_Local',
 'ACV_USD',
 'Last_Invoice_Amount_USD',
 'Lifetime_Revenue_USD',
 'Add_On_Revenue_USD',
 'Payment_Delay_Days',
 'Price_Sensitivity',
 'Competitor_Mentioned',
 'Downsell_Requested',
 'Renewal_Risk_Flag',
 'Churn',
 'Next_Quarter_Revenue_USD',
 'Total_Transactions',
 'Total_Revenue_USD',
 'Avg_Revenue_USD',
 'Total_Billed_USD',
 'Total_AddOn_Revenue',
 'Avg_Discount',
 'Avg_Tax',
 'Avg_Payment_Delay',
 'Max_Payment_Delay',
 'Avg_Daily_Active_Users',
 'Avg_Monthly_Active_Users',
 'Avg_Feature_Adoption',
 'Avg_API_Calls',
 'Avg_Licenses_Used',
 'Avg_Licenses_Purchased',
 'Avg_License_Utilization',
 'Avg_Sessions',
 'Avg_Session_Min',
 'Avg_Mobile_Sessions',
 'Avg_Integrations',
 'Avg_Automations',
 'Avg_Reports',
 'Avg_Data_Records',
 'Avg_Storage',
 'Avg_Errors',
 'Avg_Uptime',
 'Total_Events',
 'Avg_Resolution_Days',
 'Avg_Score',
 'At-Risk Alert',
 'CSAT Survey',
 'Certification Earned',
 'Champion Change',
 'Community Post',
 'Escalation',
 'Executive Business Review',
 'NPS Survey',
 'Onboarding Call',
 'Product Feedback',
 'QBR Meeting',
 'Support Ticket',
 'Training Session',
 'Unknown',
 'Webinar Attended',
 ' Chat  ',
 ' Email  ',
 ' In-App  ',
 ' In-Person  ',
 ' Phone  ',
 ' Portal  ',
 ' Video Call  ',
 'Chat',
 'Email',
 'In-App',
 'In-Person',
 'Phone',
 'Portal',
 'Video Call',
 'Critical',
 'High',
 'Low',
 'Medium',
 'Not Applicable_x',
 'Closed-No-Action',
 'Escalated',
 'Not Applicable_y',
 'Pending',
 'Resolved',
 'Workaround',
 'Negative',
 'Neutral',
 'Positive',
 'FollowUp_Count',
 'SLA_Breach_Count',
 'Manager_Escalation_Count']

In [22]:
print(churn_df.columns.tolist())

['Total_Transactions', 'Next_Quarter_Revenue_USD', 'Renewal_Risk_Flag', 'ACV_USD', 'Last_Invoice_Amount_USD', 'Avg_Revenue_USD', 'Avg_API_Calls', 'Total_Billed_USD', 'API_Calls_Monthly', 'Avg_Tax', 'Subscription_Value_Local', 'Lifetime_Revenue_USD', 'ACV_Local', 'Total_Revenue_USD', 'Total_AddOn_Revenue', 'Avg_Feature_Adoption', 'Max_Payment_Delay', 'Avg_Payment_Delay', 'Payment_Delay_Days', 'Cluster_Label', 'Feature_Adoption_Pct', 'Avg_Automations', 'NPS_Score', 'Health_Score', 'Renewal_Probability', 'Avg_Daily_Active_Users', 'Avg_Score', 'Avg_Errors', 'Avg_Session_Min', 'Negative', 'Onboarding_Completed', 'QBR_Completed_Last_6M', 'Competitor_Mentioned', 'Downsell_Requested', 'Actual_Churn', 'Predicted_Churn', 'Churn_Probability']

In [23]:
print(revenue_df.columns.tolist())

['Customer_ID', 'Geo_ID', 'Industry_ID', 'Product_ID', 'Cluster_Label', 'Account_Tier', 'Company_Size', 'Company_Age_Years', 'Employees', 'Legal_Entity_Type', 'HQ_vs_Billing', 'Tenure_Months', 'Contract_Type', 'Contract_Start_Date', 'Contract_End_Date', 'Renewal_Probability', 'CSM_Assigned', 'CSM_Name', 'Executive_Sponsor', 'Health_Score', 'Onboarding_Completed', 'QBR_Completed_Last_6M', 'Last_Training_Days_Ago', 'Licenses_Purchased', 'Daily_Active_Users', 'Feature_Adoption_Pct', 'API_Calls_Monthly', 'Mobile_Users_Pct', 'Sessions_Per_User_Day', 'Avg_Session_Minutes', 'Integrations_Count', 'Custom_Reports_Count', 'Automations_Active', 'Support_Tickets', 'Escalated_Tickets', 'CSAT_Score', 'NPS_Score', 'Subscription_Value_Local', 'Discount_Pct', 'ACV_Local', 'ACV_USD', 'Last_Invoice_Amount_USD', 'Lifetime_Revenue_USD', 'Add_On_Revenue_USD', 'Payment_Delay_Days', 'Price_Sensitivity', 'Competitor_Mentioned', 'Downsell_Requested', 'Renewal_Risk_Flag', 'Churn', 'Next_Quarter_Revenue_USD', 'Total_Transactions', 'Total_Revenue_USD', 'Avg_Revenue_USD', 'Total_Billed_USD', 'Total_AddOn_Revenue', 'Avg_Discount', 'Avg_Tax', 'Avg_Payment_Delay', 'Max_Payment_Delay', 'Avg_Daily_Active_Users', 'Avg_Monthly_Active_Users', 'Avg_Feature_Adoption', 'Avg_API_Calls', 'Avg_Licenses_Used', 'Avg_Licenses_Purchased', 'Avg_License_Utilization', 'Avg_Sessions', 'Avg_Session_Min', 'Avg_Mobile_Sessions', 'Avg_Integrations', 'Avg_Automations', 'Avg_Reports', 'Avg_Data_Records', 'Avg_Storage', 'Avg_Errors', 'Avg_Uptime', 'Total_Events', 'Avg_Resolution_Days', 'Avg_Score', 'At-Risk Alert', 'CSAT Survey', 'Certification Earned', 'Champion Change', 'Community Post', 'Escalation', 'Executive Business Review', 'NPS Survey', 'Onboarding Call', 'Product Feedback', 'QBR Meeting', 'Support Ticket', 'Training Session', 'Unknown', 'Webinar Attended', ' Chat  ', ' Email  ', ' In-App  ', ' In-Person  ', ' Phone  ', ' Portal  ', ' Video Call  ', 'Chat', 'Email', 'In-App', 'In-Person', 'Phone', 'Portal', 'Video Call', 'Critical', 'High', 'Low', 'Medium', 'Not Applicable_x', 'Closed-No-Action', 'Escalated', 'Not Applicable_y', 'Pending', 'Resolved', 'Workaround', 'Negative', 'Neutral', 'Positive', 'FollowUp_Count', 'SLA_Breach_Count', 'Manager_Escalation_Count', 'Predicted_Next_Quarter_Revenue']

In [25]:
customer_intelligence = revenue_df.copy()

In [26]:
customer_intelligence['Predicted_Churn'] = churn_df['Predicted_Churn']
customer_intelligence['Churn_Probability'] = churn_df['Churn_Probability']

In [27]:
customer_intelligence.shape

(5000, 129)

In [28]:
customer_intelligence[['Customer_ID',
                       'Predicted_Churn',
                       'Churn_Probability',
                       'Predicted_Next_Quarter_Revenue',
                       'Cluster_Label']].head()

,Customer_ID,Predicted_Churn,Churn_Probability,Predicted_Next_Quarter_Revenue,Cluster_Label
0,11177,0,4.316189e-09,36.364887,At-Risk SMB
1,14771,0,3.872796e-09,11696.725000,High-Growth Startup
2,11091,0,2.417322e-09,19385.465000,High Revenue Loyal
3,14818,1,1.000000e+00,743.993840,At-Risk SMB
4,14376,0,1.063369e-09,3344.757300,High Revenue Loyal

In [30]:
from sklearn.preprocessing import MinMaxScaler

# Select risk features
risk_features = customer_intelligence[
    ['Churn_Probability',
     'Payment_Delay_Days',
     'Renewal_Risk_Flag',
     'Support_Tickets']
].copy()

# Convert all columns to numeric
for col in risk_features.columns:
    risk_features[col] = pd.to_numeric(risk_features[col], errors='coerce')

# Fill missing values
risk_features = risk_features.fillna(0)

# Scale features
scaler = MinMaxScaler()
risk_scaled = scaler.fit_transform(risk_features)

# Calculate Risk Score
customer_intelligence['Risk_Score'] = (
      risk_scaled[:, 0] * 0.50   # Churn Probability
    + risk_scaled[:, 1] * 0.20   # Payment Delay
    + risk_scaled[:, 2] * 0.20   # Renewal Risk
    + risk_scaled[:, 3] * 0.10   # Support Tickets
) * 100

customer_intelligence['Risk_Score'] = customer_intelligence['Risk_Score'].round(2)

# View results
customer_intelligence[['Customer_ID', 'Risk_Score']].head()

   Customer_ID  Risk_Score
0        11177       10.56
1        14771        6.56
2        11091        7.36
3        14818       61.57
4        14376        7.07

In [31]:
customer_intelligence[['Renewal_Risk_Flag',
                       'Payment_Delay_Days',
                       'Support_Tickets']].dtypes

Renewal_Risk_Flag       str
Payment_Delay_Days    int64
Support_Tickets       int64
dtype: object

In [32]:
# Features for revenue potential
revenue_features = customer_intelligence[
    ['Predicted_Next_Quarter_Revenue',
     'Health_Score',
     'Feature_Adoption_Pct',
     'Renewal_Probability']
].copy()

# Scale to 0-1
scaler = MinMaxScaler()
revenue_scaled = scaler.fit_transform(revenue_features)

# Revenue Potential Score
customer_intelligence['Revenue_Potential_Score'] = (
      revenue_scaled[:,0] * 0.50
    + revenue_scaled[:,1] * 0.20
    + revenue_scaled[:,2] * 0.20
    + revenue_scaled[:,3] * 0.10
) * 100

customer_intelligence['Revenue_Potential_Score'] = (
    customer_intelligence['Revenue_Potential_Score'].round(2)
)

In [33]:
customer_intelligence[
    ['Customer_ID',
     'Predicted_Next_Quarter_Revenue',
     'Revenue_Potential_Score']
].head()

   Customer_ID  Predicted_Next_Quarter_Revenue  Revenue_Potential_Score
0        11177                       36.364887                    17.15
1        14771                    11696.725000                    40.76
2        11091                    19385.465000                    58.19
3        14818                      743.993840                    13.28
4        14376                     3344.757300                    47.53

In [34]:
# Calculate Engagement Score
customer_intelligence['Engagement_Score'] = (
      customer_intelligence['Health_Score'] * 0.40
    + customer_intelligence['Feature_Adoption_Pct'] * 0.40
    + (
        customer_intelligence['Daily_Active_Users']
        / customer_intelligence['Daily_Active_Users'].max()
      ) * 100 * 0.20
).round(2)

# Categorize Engagement Level
customer_intelligence['Engagement_Level'] = np.where(
    customer_intelligence['Engagement_Score'] >= 75,
    'High',
    np.where(
        customer_intelligence['Engagement_Score'] >= 50,
        'Medium',
        'Low'
    )
)

In [35]:
customer_intelligence[
    ['Customer_ID',
     'Engagement_Score',
     'Engagement_Level']
].head()

   Customer_ID  Engagement_Score Engagement_Level
0        11177             31.63              Low
1        14771             44.09              Low
2        11091             70.76           Medium
3        14818             18.29              Low
4        14376             81.95             High

In [36]:
customer_profile = customer_intelligence[[
    'Customer_ID',
    'Cluster_Label',
    'Predicted_Churn',
    'Churn_Probability',
    'Predicted_Next_Quarter_Revenue',
    'Risk_Score',
    'Revenue_Potential_Score',
    'Engagement_Score',
    'Engagement_Level'
]]

customer_profile.head()

,Customer_ID,Cluster_Label,Predicted_Churn,Churn_Probability,Predicted_Next_Quarter_Revenue,Risk_Score,Revenue_Potential_Score,Engagement_Score,Engagement_Level
0,11177,At-Risk SMB,0,4.316189e-09,36.364887,10.56,17.15,31.63,Low
1,14771,High-Growth Startup,0,3.872796e-09,11696.725000,6.56,40.76,44.09,Low
2,11091,High Revenue Loyal,0,2.417322e-09,19385.465000,7.36,58.19,70.76,Medium
3,14818,At-Risk SMB,1,1.000000e+00,743.993840,61.57,13.28,18.29,Low
4,14376,High Revenue Loyal,0,1.063369e-09,3344.757300,7.07,47.53,81.95,High

In [37]:
customer_profile.to_csv(
    "Customer_Intelligence_Profile.csv",
    index=False
)

print("Customer Intelligence Profile saved successfully.")

Customer Intelligence Profile saved successfully.

In [38]:
customer_profile.to_json(
    "Customer_Intelligence_Profile.json",
    orient="records",
    indent=4
)

print("JSON file saved successfully.")

JSON file saved successfully.